# Generated by Django 5.2.6 on 2025-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.URLField()),
            ],
        ),
    ]
