# Generated by Django 5.2.6 on 2025-09-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_libro_autor_alter_libro_imagen_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
